/* ══════════════════════════════════════════════════════════
   Wadjet-Eye AI — Branding, Pricing & Auth Module v17.0.0
   White-labeling, SSO/OAuth, Pricing Plans, TLS/Security
   ══════════════════════════════════════════════════════════ */

/* ─── BRANDING STORE (persists in memory) ─── */
const BRANDING_STORE = {
  platform_name: 'Wadjet-Eye AI',
  platform_tagline: 'AI-Agentic Cyber Threat Intelligence Platform',
  platform_version: 'v17.0.0',
  logo_icon: 'fa-eye',
  primary_color: '#1d6ae5',
  accent_color: '#c9a227',
  sidebar_color: '#080c14',
  login_bg: 'grid',
  report_header: 'Wadjet-Eye AI — Confidential Threat Intelligence Report',
  report_footer: 'Generated by Wadjet-Eye AI · CONFIDENTIAL — DO NOT DISTRIBUTE',
  favicon_emoji: '👁️',
  support_email: 'support@wadjet-eye-ai.com',
  custom_domain: 'https://wadjet-eye-ai.vercel.app',
};

/* ─── PRICING PLANS ─── */
const PRICING_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price_monthly: 299,
    price_annual: 2990,
    color: '#22c55e',
    icon: '🚀',
    badge: null,
    desc: 'For small security teams getting started with threat intelligence.',
    limits: { users: 3, tenants: 1, collectors: 10, iocs_per_day: 1000, reports_per_month: 5 },
    features: [
      '3 user accounts',
      '1 tenant',
      '10 threat collectors',
      '1,000 IOCs/day',
      'Command Center dashboard',
      'Findings & Campaigns',
      'Cyber News feed',
      'Basic MITRE ATT&CK map',
      'Email support',
      '5 reports/month',
      'Community playbooks',
    ],
    not_included: ['AI Orchestrator','Dark Web Intel','SOAR Automation','Executive Dashboard','API Access','White-labeling','SLA guarantee','Dedicated CSM']
  },
  {
    id: 'professional',
    name: 'Professional',
    price_monthly: 799,
    price_annual: 7990,
    color: '#3b82f6',
    icon: '⚡',
    badge: 'Most Popular',
    desc: 'For growing security teams that need full threat intel capabilities.',
    limits: { users: 10, tenants: 3, collectors: 30, iocs_per_day: 10000, reports_per_month: 50 },
    features: [
      '10 user accounts',
      '3 tenants',
      '30 threat collectors',
      '10,000 IOCs/day',
      'All Starter features',
      'AI Orchestrator (Qwen3:8B)',
      'Dark Web Intelligence',
      'IOC Database & Search',
      'Detection Engineering',
      'Threat Hunting Workspace',
      'Case Management',
      'SOAR Automation',
      'Kill Chain Visualization',
      'Geo Threat Distribution',
      'Full MITRE ATT&CK Navigator',
      'RBAC with 5 roles',
      'REST API access',
      '50 reports/month',
      '48h SLA',
    ],
    not_included: ['White-labeling','Custom domain','Executive briefings','Dedicated CSM','Custom integrations']
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price_monthly: null,
    price_annual: null,
    color: '#a855f7',
    icon: '🏢',
    badge: 'Custom Pricing',
    desc: 'For MSSPs and enterprise security operations centers.',
    limits: { users: 'Unlimited', tenants: 'Unlimited', collectors: 47, iocs_per_day: 'Unlimited', reports_per_month: 'Unlimited' },
    features: [
      'Unlimited users',
      'Unlimited tenants',
      'All 47 threat collectors',
      'Unlimited IOCs',
      'All Professional features',
      '🎨 Full white-labeling',
      '🌐 Custom domain',
      '🤖 Priority AI (GPT-4o + Claude)',
      '📊 Executive Dashboard',
      '🔗 Custom SIEM/EDR integrations',
      '🔐 SSO (SAML/Azure AD/Okta)',
      '👥 Unlimited RBAC roles',
      '📞 Dedicated Customer Success Manager',
      '🚨 4h SLA guarantee',
      '📱 Mobile app access',
      '🔒 Private cloud deployment',
      '📋 Compliance reports (ISO 27001, SOC2, NIST)',
      '🧪 Purple team simulation',
    ],
    not_included: []
  }
];

/* ══════════════════════════════════════════════
   RENDER BRANDING PAGE
   ══════════════════════════════════════════════ */
function renderBranding() {
  const container = document.getElementById('brandingWrap');
  if (!container) return;

  container.innerHTML = `
    <div style="margin-bottom:16px;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:10px;">
      <div>
        <h2 style="font-size:18px;font-weight:800;display:flex;align-items:center;gap:8px;">
          <span style="width:32px;height:32px;background:linear-gradient(135deg,#a855f7,#ec4899);border-radius:8px;display:flex;align-items:center;justify-content:center;font-size:14px;">🎨</span>
          White-Labeling & Branding
        </h2>
        <p style="font-size:11px;color:var(--text-muted);margin-top:3px;">Customize the platform with your brand · Changes apply to login, console and reports · v17.0.0</p>
      </div>
      <div style="display:flex;gap:8px;">
        <button class="btn-primary" onclick="saveBranding()"><i class="fas fa-save"></i> Save Branding</button>
        <button class="btn-primary" style="background:rgba(100,116,139,0.2);border-color:rgba(100,116,139,0.4);" onclick="resetBranding()"><i class="fas fa-undo"></i> Reset Default</button>
        <button class="btn-primary" style="background:rgba(34,197,94,0.15);border-color:rgba(34,197,94,0.3);" onclick="previewBranding()"><i class="fas fa-eye"></i> Preview</button>
      </div>
    </div>

    <!-- Live Preview Banner -->
    <div id="brandingPreviewBanner" style="display:none;background:linear-gradient(135deg,rgba(168,85,247,0.15),rgba(236,72,153,0.1));border:1px solid rgba(168,85,247,0.4);border-radius:10px;padding:12px 16px;margin-bottom:16px;display:flex;align-items:center;gap:10px;">
      <i class="fas fa-eye" style="color:#c084fc;font-size:18px;"></i>
      <div>
        <div style="font-size:12px;font-weight:700;color:#c084fc;">Live Preview Mode Active</div>
        <div style="font-size:10px;color:var(--text-muted);">Branding changes are previewed below. Click Save to apply permanently.</div>
      </div>
    </div>

    <div style="display:grid;grid-template-columns:1fr 340px;gap:16px;">
      <!-- Branding Settings -->
      <div style="display:flex;flex-direction:column;gap:14px;">

        <!-- Identity -->
        <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:12px;padding:18px;">
          <div style="font-size:13px;font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:8px;"><i class="fas fa-id-card" style="color:#3b82f6;"></i> Platform Identity</div>
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">PLATFORM NAME *</label>
              <input id="br_name" class="settings-input" style="width:100%;" value="${BRANDING_STORE.platform_name}" oninput="updateBrandingPreview()" placeholder="Your Company SOC" /></div>
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">TAGLINE</label>
              <input id="br_tagline" class="settings-input" style="width:100%;" value="${BRANDING_STORE.platform_tagline}" oninput="updateBrandingPreview()" placeholder="Your threat intelligence platform" /></div>
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">SUPPORT EMAIL</label>
              <input id="br_email" class="settings-input" style="width:100%;" value="${BRANDING_STORE.support_email}" placeholder="soc@yourcompany.com" /></div>
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">CUSTOM DOMAIN <span style="color:#a855f7;font-size:9px;">ENTERPRISE</span></label>
              <input id="br_domain" class="settings-input" style="width:100%;" value="${BRANDING_STORE.custom_domain}" placeholder="soc.yourcompany.com" /></div>
          </div>
        </div>

        <!-- Colors -->
        <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:12px;padding:18px;">
          <div style="font-size:13px;font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:8px;"><i class="fas fa-palette" style="color:#ec4899;"></i> Color Scheme</div>
          <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px;">
            ${[
              {id:'br_primary',label:'Primary Color',val:BRANDING_STORE.primary_color},
              {id:'br_accent',label:'Accent Color',val:BRANDING_STORE.accent_color},
              {id:'br_sidebar',label:'Sidebar Background',val:BRANDING_STORE.sidebar_color},
            ].map(c=>`
              <div>
                <label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:6px;">${c.label}</label>
                <div style="display:flex;gap:8px;align-items:center;">
                  <input type="color" id="${c.id}" value="${c.val}" style="width:40px;height:36px;border:1px solid var(--border);border-radius:var(--radius);background:var(--bg-input);cursor:pointer;padding:2px;" oninput="updateBrandingPreview()" />
                  <input class="settings-input" value="${c.val}" style="flex:1;" oninput="document.getElementById('${c.id}').value=this.value;updateBrandingPreview();" />
                </div>
              </div>`).join('')}
          </div>
          <div style="margin-top:12px;">
            <div style="font-size:11px;color:var(--text-muted);font-weight:700;margin-bottom:8px;">PRESET THEMES</div>
            <div style="display:flex;gap:8px;flex-wrap:wrap;">
              ${[
                {name:'Dark Blue (Default)',p:'#3b82f6',a:'#22d3ee',s:'#0d1421'},
                {name:'Cyberpunk',p:'#22d3ee',a:'#a855f7',s:'#0a0a1a'},
                {name:'Red Alert',p:'#ef4444',a:'#f97316',s:'#120808'},
                {name:'Green Ops',p:'#22c55e',a:'#10b981',s:'#051a0d'},
                {name:'Corporate Gray',p:'#64748b',a:'#94a3b8',s:'#111827'},
              ].map(t=>`
                <button onclick="applyTheme('${t.p}','${t.a}','${t.s}')" style="padding:5px 10px;background:${t.p}22;border:1px solid ${t.p}44;border-radius:6px;color:${t.p};font-size:10px;cursor:pointer;font-weight:600;">
                  <span style="width:8px;height:8px;border-radius:50%;background:${t.p};display:inline-block;margin-right:4px;"></span>${t.name}
                </button>`).join('')}
            </div>
          </div>
        </div>

        <!-- Logo & Assets -->
        <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:12px;padding:18px;">
          <div style="font-size:13px;font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:8px;"><i class="fas fa-image" style="color:#f59e0b;"></i> Logo & Assets</div>
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;">
            <div>
              <label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:6px;">LOGO ICON</label>
              <div style="display:flex;flex-wrap:wrap;gap:6px;">
                ${['fa-shield-alt','fa-shield','fa-lock','fa-eye','fa-crosshairs','fa-bug','fa-server','fa-network-wired','fa-satellite'].map(ic=>`
                  <button onclick="this.parentElement.querySelectorAll('button').forEach(b=>b.style.background='var(--bg-surface)');this.style.background='rgba(59,130,246,0.2)';BRANDING_STORE.logo_icon='${ic}';updateBrandingPreview();" style="width:34px;height:34px;background:${BRANDING_STORE.logo_icon===ic?'rgba(59,130,246,0.2)':'var(--bg-surface)'};border:1px solid var(--border);border-radius:6px;cursor:pointer;color:var(--text-primary);">
                    <i class="fas ${ic}"></i>
                  </button>`).join('')}
              </div>
            </div>
            <div>
              <label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:6px;">CUSTOM LOGO URL <span style="color:#a855f7;font-size:9px;">ENTERPRISE</span></label>
              <input class="settings-input" style="width:100%;" placeholder="https://yourcompany.com/logo.png" />
              <div style="font-size:10px;color:var(--text-muted);margin-top:4px;">PNG/SVG recommended · Max 512×512px</div>
            </div>
          </div>
        </div>

        <!-- Reports -->
        <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:12px;padding:18px;">
          <div style="font-size:13px;font-weight:700;margin-bottom:14px;display:flex;align-items:center;gap:8px;"><i class="fas fa-file-alt" style="color:#22d3ee;"></i> Report Branding</div>
          <div style="display:flex;flex-direction:column;gap:10px;">
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">REPORT HEADER</label>
              <input id="br_rpt_header" class="settings-input" style="width:100%;" value="${BRANDING_STORE.report_header}" /></div>
            <div><label style="font-size:11px;color:var(--text-muted);font-weight:700;display:block;margin-bottom:4px;">REPORT FOOTER</label>
              <input id="br_rpt_footer" class="settings-input" style="width:100%;" value="${BRANDING_STORE.report_footer}" /></div>
            <div style="display:flex;align-items:center;justify-content:space-between;padding:10px;background:var(--bg-surface);border:1px solid var(--border);border-radius:var(--radius);">
              <div><div style="font-size:12px;font-weight:600;">Include logo in reports</div><div style="font-size:10px;color:var(--text-muted);">Add your logo to PDF header</div></div>
              <div class="toggle-switch on" onclick="this.classList.toggle('on')"></div>
            </div>
            <div style="display:flex;align-items:center;justify-content:space-between;padding:10px;background:var(--bg-surface);border:1px solid var(--border);border-radius:var(--radius);">
              <div><div style="font-size:12px;font-weight:600;">Watermark exports</div><div style="font-size:10px;color:var(--text-muted);">Stamp user name on all exports</div></div>
              <div class="toggle-switch on" onclick="this.classList.toggle('on')"></div>
            </div>
          </div>
        </div>
      </div>

      <!-- Live Preview -->
      <div style="position:sticky;top:0;">
        <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:12px;padding:16px;">
          <div style="font-size:12px;font-weight:700;margin-bottom:12px;color:var(--text-muted);text-transform:uppercase;letter-spacing:1px;">Live Preview</div>
          <!-- Mini Login Preview -->
          <div id="brandPreviewCard" style="background:var(--bg-base);border:1px solid var(--border);border-radius:10px;padding:14px;margin-bottom:12px;">
            <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
              <div id="prevLogoIcon" style="width:28px;height:28px;background:linear-gradient(135deg,${BRANDING_STORE.primary_color},${BRANDING_STORE.accent_color});border-radius:7px;display:flex;align-items:center;justify-content:center;font-size:13px;">
                <i class="fas ${BRANDING_STORE.logo_icon}" style="color:white;"></i>
              </div>
              <div>
                <div id="prevPlatformName" style="font-size:12px;font-weight:700;color:var(--text-primary);">${BRANDING_STORE.platform_name}</div>
                <div id="prevTagline" style="font-size:9px;color:var(--text-muted);">${BRANDING_STORE.platform_tagline}</div>
              </div>
            </div>
            <div style="height:1px;background:var(--border);margin:8px 0;"></div>
            <div style="font-size:10px;color:var(--text-muted);margin-bottom:4px;">Preview login button:</div>
            <button id="prevLoginBtn" style="width:100%;padding:7px;background:${BRANDING_STORE.primary_color};border:none;border-radius:6px;color:white;font-size:11px;font-weight:700;cursor:pointer;">
              <i class="fas fa-sign-in-alt"></i> Sign In Securely
            </button>
          </div>
          <!-- Mini Sidebar Preview -->
          <div style="background:${BRANDING_STORE.sidebar_color};border:1px solid var(--border);border-radius:8px;padding:10px;">
            <div style="font-size:9px;color:var(--text-muted);margin-bottom:6px;text-transform:uppercase;letter-spacing:1px;">Sidebar Preview</div>
            ${['Command Center','Findings','Threat Actors','AI Orchestrator'].map((item,i) => `
              <div style="padding:5px 8px;border-radius:5px;font-size:10px;font-weight:${i===0?'700':'500'};color:${i===0?BRANDING_STORE.primary_color:'var(--text-secondary)'};background:${i===0?BRANDING_STORE.primary_color+'22':'transparent'};margin-bottom:2px;border-left:${i===0?`2px solid ${BRANDING_STORE.primary_color}`:'2px solid transparent'};">
                ${item}
              </div>`).join('')}
          </div>
        </div>
      </div>
    </div>
  `;
}

function updateBrandingPreview() {
  const name    = document.getElementById('br_name')?.value || BRANDING_STORE.platform_name;
  const tagline = document.getElementById('br_tagline')?.value || BRANDING_STORE.platform_tagline;
  const primary = document.getElementById('br_primary')?.value || BRANDING_STORE.primary_color;
  const accent  = document.getElementById('br_accent')?.value || BRANDING_STORE.accent_color;
  const el = id => document.getElementById(id);
  if (el('prevPlatformName')) el('prevPlatformName').textContent = name;
  if (el('prevTagline')) el('prevTagline').textContent = tagline;
  if (el('prevLoginBtn')) el('prevLoginBtn').style.background = primary;
  if (el('prevLogoIcon')) el('prevLogoIcon').style.background = `linear-gradient(135deg,${primary},${accent})`;
}

function applyTheme(primary, accent, sidebar) {
  document.getElementById('br_primary').value = primary;
  document.getElementById('br_accent').value = accent;
  document.getElementById('br_sidebar').value = sidebar;
  updateBrandingPreview();
  showToast('Theme applied — click Save to confirm','info');
}

function saveBranding() {
  BRANDING_STORE.platform_name   = document.getElementById('br_name')?.value.trim() || BRANDING_STORE.platform_name;
  BRANDING_STORE.platform_tagline = document.getElementById('br_tagline')?.value.trim() || BRANDING_STORE.platform_tagline;
  BRANDING_STORE.primary_color   = document.getElementById('br_primary')?.value || BRANDING_STORE.primary_color;
  BRANDING_STORE.accent_color    = document.getElementById('br_accent')?.value || BRANDING_STORE.accent_color;
  BRANDING_STORE.sidebar_color   = document.getElementById('br_sidebar')?.value || BRANDING_STORE.sidebar_color;
  BRANDING_STORE.support_email   = document.getElementById('br_email')?.value.trim() || BRANDING_STORE.support_email;
  BRANDING_STORE.custom_domain   = document.getElementById('br_domain')?.value.trim() || '';
  BRANDING_STORE.report_header   = document.getElementById('br_rpt_header')?.value.trim() || BRANDING_STORE.report_header;
  BRANDING_STORE.report_footer   = document.getElementById('br_rpt_footer')?.value.trim() || BRANDING_STORE.report_footer;
  // Apply to sidebar logo name
  const logoName = document.querySelector('.logo-name');
  if (logoName) logoName.textContent = BRANDING_STORE.platform_name;
  document.title = `${BRANDING_STORE.platform_name} — Threat Intelligence Platform`;
  document.documentElement.style.setProperty('--accent-blue', BRANDING_STORE.primary_color);
  document.documentElement.style.setProperty('--accent-cyan', BRANDING_STORE.accent_color);
  showToast(`✅ Branding saved — "${BRANDING_STORE.platform_name}" applied!`, 'success');
}

function resetBranding() {
  Object.assign(BRANDING_STORE, {
    platform_name:'ThreatPilot AI', platform_tagline:'AI-Agentic Threat Intelligence Platform',
    primary_color:'#3b82f6', accent_color:'#22d3ee', sidebar_color:'#0d1421',
    logo_icon:'fa-shield-alt', report_header:'ThreatPilot AI — Confidential Threat Intelligence Report',
    report_footer:'Generated by ThreatPilot AI · CONFIDENTIAL — DO NOT DISTRIBUTE',
  });
  document.documentElement.style.removeProperty('--accent-blue');
  document.documentElement.style.removeProperty('--accent-cyan');
  const logoName = document.querySelector('.logo-name');
  if (logoName) logoName.textContent = 'ThreatPilot AI';
  document.title = 'ThreatPilot AI — AI-Agentic Threat Intelligence Platform';
  renderBranding();
  showToast('Branding reset to ThreatPilot AI defaults','info');
}

function previewBranding() {
  updateBrandingPreview();
  const banner = document.getElementById('brandingPreviewBanner');
  if (banner) { banner.style.display='flex'; setTimeout(()=>banner.style.display='none',4000); }
  showToast('Preview updated — check the sidebar preview panel','info');
}

/* ══════════════════════════════════════════════
   RENDER PRICING PAGE
   ══════════════════════════════════════════════ */
function renderPricing() {
  const container = document.getElementById('pricingWrap');
  if (!container) return;

  container.innerHTML = `
    <div style="text-align:center;margin-bottom:32px;">
      <h2 style="font-size:24px;font-weight:900;background:linear-gradient(135deg,#3b82f6,#a855f7,#22d3ee);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:8px;">Choose Your Plan</h2>
      <p style="font-size:13px;color:var(--text-muted);">Scale your threat intelligence operations · All plans include a 14-day free trial</p>
      <div style="display:flex;align-items:center;justify-content:center;gap:12px;margin-top:16px;">
        <span style="font-size:12px;color:var(--text-secondary);">Monthly</span>
        <div class="toggle-switch on" id="billingToggle" onclick="this.classList.toggle('on');toggleBillingCycle()"></div>
        <span style="font-size:12px;color:var(--text-secondary);">Annual <span style="color:#22c55e;font-weight:700;font-size:11px;">Save 20%</span></span>
      </div>
    </div>

    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:20px;max-width:1100px;margin:0 auto;" id="pricingGrid">
      ${PRICING_PLANS.map(plan => `
        <div style="background:var(--bg-card);border:${plan.badge==='Most Popular'?`2px solid ${plan.color}`:`1px solid var(--border)`};border-radius:16px;padding:24px;position:relative;display:flex;flex-direction:column;transition:transform 0.2s ease;" onmouseover="this.style.transform='translateY(-4px)'" onmouseout="this.style.transform='none'">
          ${plan.badge?`<div style="position:absolute;top:-12px;left:50%;transform:translateX(-50%);background:${plan.color};color:white;padding:4px 16px;border-radius:20px;font-size:10px;font-weight:800;white-space:nowrap;">${plan.badge}</div>`:''}
          <div style="text-align:center;margin-bottom:20px;">
            <div style="font-size:36px;margin-bottom:8px;">${plan.icon}</div>
            <div style="font-size:18px;font-weight:900;color:${plan.color};">${plan.name}</div>
            <div style="font-size:11px;color:var(--text-muted);margin-top:4px;">${plan.desc}</div>
          </div>
          <div style="text-align:center;margin-bottom:20px;padding:16px;background:${plan.color}10;border-radius:10px;">
            <div id="price-${plan.id}" style="font-size:36px;font-weight:900;color:${plan.color};">
              ${plan.price_monthly ? `$${plan.price_monthly}<span style="font-size:14px;font-weight:400;color:var(--text-muted);">/mo</span>` : `<span style="font-size:22px;">Custom</span>`}
            </div>
            ${plan.price_annual ? `<div style="font-size:10px;color:var(--text-muted);margin-top:4px;" id="priceNote-${plan.id}">Billed monthly · $${plan.price_annual}/yr if annual</div>` : `<div style="font-size:11px;color:var(--text-muted);">Contact sales for pricing</div>`}
          </div>
          <div style="flex:1;">
            <div style="font-size:10px;color:var(--text-muted);font-weight:700;margin-bottom:8px;">INCLUDES:</div>
            <div style="display:flex;flex-direction:column;gap:5px;margin-bottom:16px;">
              ${plan.features.map(f=>`
                <div style="display:flex;align-items:center;gap:8px;font-size:11px;">
                  <i class="fas fa-check" style="color:${plan.color};font-size:9px;flex-shrink:0;"></i>
                  <span style="color:var(--text-secondary);">${f}</span>
                </div>`).join('')}
              ${plan.not_included.map(f=>`
                <div style="display:flex;align-items:center;gap:8px;font-size:11px;opacity:0.4;">
                  <i class="fas fa-times" style="color:var(--text-muted);font-size:9px;flex-shrink:0;"></i>
                  <span style="color:var(--text-muted);text-decoration:line-through;">${f}</span>
                </div>`).join('')}
            </div>
          </div>
          <div style="margin-top:12px;">
            ${plan.price_monthly ? `
              <button style="width:100%;padding:10px;background:${plan.color};border:none;border-radius:8px;color:white;font-size:13px;font-weight:700;cursor:pointer;margin-bottom:6px;transition:opacity 0.2s;" onmouseover="this.style.opacity='0.85'" onmouseout="this.style.opacity='1'" onclick="startTrial('${plan.id}')">
                Start Free Trial
              </button>
              <button style="width:100%;padding:8px;background:transparent;border:1px solid ${plan.color};border-radius:8px;color:${plan.color};font-size:11px;cursor:pointer;" onclick="showToast('Opening ${plan.name} demo...','info')">
                View Demo
              </button>` : `
              <button style="width:100%;padding:10px;background:linear-gradient(135deg,#a855f7,#ec4899);border:none;border-radius:8px;color:white;font-size:13px;font-weight:700;cursor:pointer;margin-bottom:6px;" onclick="contactSales()">
                Contact Sales
              </button>
              <button style="width:100%;padding:8px;background:transparent;border:1px solid #a855f7;border-radius:8px;color:#c084fc;font-size:11px;cursor:pointer;" onclick="bookDemo()">
                Book a Demo
              </button>`}
          </div>
        </div>`).join('')}
    </div>

    <!-- FAQ -->
    <div style="max-width:900px;margin:40px auto 0;">
      <h3 style="font-size:18px;font-weight:800;text-align:center;margin-bottom:20px;">Frequently Asked Questions</h3>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;">
        ${[
          {q:'Can I switch plans anytime?',a:'Yes. Upgrade or downgrade your plan at any time. Changes take effect at the start of the next billing cycle.'},
          {q:'Is my data isolated from other tenants?',a:'Absolutely. ThreatPilot uses strict tenant isolation — your data is never shared with or visible to other organizations.'},
          {q:'Do you support SAML/SSO?',a:'SSO is available on the Enterprise plan with support for SAML 2.0, Azure AD, Okta, Google Workspace and custom OIDC.'},
          {q:'What APIs are included?',a:'The Professional and Enterprise plans include REST API access for IOC enrichment, findings, and collector management.'},
          {q:'Can I white-label the platform?',a:'White-labeling (custom name, logo, colors, domain) is available exclusively on the Enterprise plan.'},
          {q:'Is there a self-hosted option?',a:'Yes. Enterprise customers can deploy ThreatPilot on-premises or in a private cloud (AWS, Azure, GCP).'},
        ].map(faq=>`
          <div style="background:var(--bg-card);border:1px solid var(--border);border-radius:10px;padding:14px;">
            <div style="font-size:12px;font-weight:700;margin-bottom:6px;color:var(--text-primary);">❓ ${faq.q}</div>
            <div style="font-size:11px;color:var(--text-secondary);line-height:1.6;">${faq.a}</div>
          </div>`).join('')}
      </div>
    </div>
  `;
}

function toggleBillingCycle() {
  const isAnnual = document.getElementById('billingToggle')?.classList.contains('on');
  PRICING_PLANS.forEach(plan => {
    const priceEl = document.getElementById(`price-${plan.id}`);
    const noteEl = document.getElementById(`priceNote-${plan.id}`);
    if (!priceEl || !plan.price_monthly) return;
    if (isAnnual) {
      const annualMonthly = Math.round(plan.price_annual / 12);
      priceEl.innerHTML = `$${annualMonthly}<span style="font-size:14px;font-weight:400;color:var(--text-muted);">/mo</span>`;
      if (noteEl) noteEl.textContent = `Billed annually · $${plan.price_annual}/yr`;
    } else {
      priceEl.innerHTML = `$${plan.price_monthly}<span style="font-size:14px;font-weight:400;color:var(--text-muted);">/mo</span>`;
      if (noteEl) noteEl.textContent = `Billed monthly · $${plan.price_annual}/yr if annual`;
    }
  });
}

function startTrial(planId) {
  const plan = PRICING_PLANS.find(p=>p.id===planId);
  showToast(`🎉 Starting 14-day free trial for ${plan.name} plan!`,'success');
  setTimeout(()=>showToast('Check your email to confirm your trial account','info'),1500);
}

function contactSales() {
  showToast('Opening Calendly for Enterprise sales...','info');
  window.open('mailto:sales@threatpilot.ai?subject=Enterprise Inquiry','_blank');
}

function bookDemo() {
  showToast('Opening demo booking...','info');
}

/* ══════════════════════════════════════════════
   LOGIN PAGE ENHANCEMENTS — OAuth + TLS
   ══════════════════════════════════════════════ */
function enhanceLoginPage() {
  const loginCard = document.querySelector('.login-card');
  if (!loginCard) return;

  // Add TLS badge
  const tlsBadge = document.createElement('div');
  tlsBadge.innerHTML = `
    <div style="display:flex;align-items:center;justify-content:center;gap:6px;padding:6px 12px;background:rgba(34,197,94,0.08);border:1px solid rgba(34,197,94,0.25);border-radius:6px;margin-bottom:12px;">
      <i class="fas fa-lock" style="color:#22c55e;font-size:11px;"></i>
      <span style="font-size:10px;color:#4ade80;font-weight:600;">TLS 1.3 Encrypted · Zero-Knowledge Auth · SOC2 Compliant</span>
      <i class="fas fa-certificate" style="color:#22c55e;font-size:11px;"></i>
    </div>`;
  const loginBtn = loginCard.querySelector('.login-btn');
  if (loginBtn) loginCard.insertBefore(tlsBadge, loginBtn);

  // Add OAuth divider and buttons
  const oauthDiv = document.createElement('div');
  oauthDiv.innerHTML = `
    <div style="display:flex;align-items:center;gap:8px;margin:12px 0;">
      <div style="flex:1;height:1px;background:var(--border);"></div>
      <span style="font-size:10px;color:var(--text-muted);white-space:nowrap;">or sign in with</span>
      <div style="flex:1;height:1px;background:var(--border);"></div>
    </div>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px;margin-bottom:12px;">
      <button class="oauth-btn" onclick="loginWithOAuth('Google')" style="display:flex;align-items:center;justify-content:center;gap:6px;padding:8px;background:var(--bg-elevated);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);cursor:pointer;font-size:11px;font-weight:600;transition:all 0.2s;">
        <svg width="14" height="14" viewBox="0 0 24 24"><path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/><path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/><path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/><path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/></svg>
        Google
      </button>
      <button class="oauth-btn" onclick="loginWithOAuth('Microsoft')" style="display:flex;align-items:center;justify-content:center;gap:6px;padding:8px;background:var(--bg-elevated);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);cursor:pointer;font-size:11px;font-weight:600;transition:all 0.2s;">
        <svg width="14" height="14" viewBox="0 0 24 24"><rect x="1" y="1" width="10" height="10" fill="#F25022"/><rect x="13" y="1" width="10" height="10" fill="#7FBA00"/><rect x="1" y="13" width="10" height="10" fill="#00A4EF"/><rect x="13" y="13" width="10" height="10" fill="#FFB900"/></svg>
        Microsoft
      </button>
      <button class="oauth-btn" onclick="loginWithOAuth('GitHub')" style="display:flex;align-items:center;justify-content:center;gap:6px;padding:8px;background:var(--bg-elevated);border:1px solid var(--border);border-radius:var(--radius);color:var(--text-primary);cursor:pointer;font-size:11px;font-weight:600;transition:all 0.2s;">
        <i class="fab fa-github" style="font-size:14px;"></i>
        GitHub
      </button>
    </div>
    <div style="display:flex;align-items:center;gap:6px;justify-content:center;margin-top:8px;">
      <i class="fas fa-shield-alt" style="color:var(--text-muted);font-size:10px;"></i>
      <span style="font-size:10px;color:var(--text-muted);">Protected by TLS 1.3 · Session timeout: 8h · Audit logged</span>
    </div>`;
  if (loginBtn) loginCard.insertBefore(oauthDiv, loginBtn.nextSibling);
}

function loginWithOAuth(provider) {
  // OAuth is handled server-side; redirect to the real login flow
  showToast(`${provider} SSO is not yet configured — use email/password to sign in.`, 'warning');
}
